package cn.lnkdoc.sdk.uia.instance.weibo.domain.user

import cn.lnkdoc.sdk.uia.serializer.annotation.UiaJsonField


@Suppress("unused", "MemberVisibilityCanBePrivate")
class Status {
    @set:UiaJsonField(name = "ad_marked")
    var adMarked: Boolean? = null
    @set:UiaJsonField(name = "annotations")
    var annotations: List<Annotation>? = null
    @set:UiaJsonField(name = "attitudes_count")
    var attitudesCount: Int? = null
    @set:UiaJsonField(name = "biz_feature")
    var bizFeature: Int? = null
    @set:UiaJsonField(name = "biz_ids")
    var bizIds: List<Int>? = null
    @set:UiaJsonField(name = "can_edit")
    var canEdit: Boolean? = null
    @set:UiaJsonField(name = "can_reprint")
    var canReprint: Boolean? = null
    @set:UiaJsonField(name = "comment_manage_info")
    var commentManageInfo: CommentManageInfo? = null
    @set:UiaJsonField(name = "comments_count")
    var commentsCount: Int? = null
    @set:UiaJsonField(name = "content_auth")
    var contentAuth: Int? = null
    @set:UiaJsonField(name = "created_at")
    var createdAt: String? = null
    @set:UiaJsonField(name = "darwin_tags")
    var darwinTags: List<Any>? = null
    @set:UiaJsonField(name = "favorited")
    var favorited: Boolean? = null
    @set:UiaJsonField(name = "geo")
    var geo: Any? = null
    @set:UiaJsonField(name = "gif_ids")
    var gifIds: String? = null
    @set:UiaJsonField(name = "hasActionTypeCard")
    var hasActionTypeCard: Int? = null
    @set:UiaJsonField(name = "hide_flag")
    var hideFlag: Int? = null
    @set:UiaJsonField(name = "hot_page")
    var hotPage: HotPage? = null
    @set:UiaJsonField(name = "hot_weibo_tags")
    var hotWeiboTags: List<Any>? = null
    @set:UiaJsonField(name = "id")
    var id: Long? = null
    @set:UiaJsonField(name = "idstr")
    var idstr: String? = null
    @set:UiaJsonField(name = "in_reply_to_screen_name")
    var inReplyToScreenName: String? = null
    @set:UiaJsonField(name = "in_reply_to_status_id")
    var inReplyToStatusId: String? = null
    @set:UiaJsonField(name = "in_reply_to_user_id")
    var inReplyToUserId: String? = null
    @set:UiaJsonField(name = "isLongText")
    var isLongText: Boolean? = null
    @set:UiaJsonField(name = "is_paid")
    var isPaid: Boolean? = null
    @set:UiaJsonField(name = "is_show_bulletin")
    var isShowBulletin: Int? = null
    @set:UiaJsonField(name = "item_category")
    var itemCategory: String? = null
    @set:UiaJsonField(name = "mblog_vip_type")
    var mblogVipType: Int? = null
    @set:UiaJsonField(name = "mblogtype")
    var mblogtype: Int? = null
    @set:UiaJsonField(name = "mid")
    var mid: String? = null
    @set:UiaJsonField(name = "mlevel")
    var mlevel: Int? = null
    @set:UiaJsonField(name = "more_info_type")
    var moreInfoType: Int? = null
    @set:UiaJsonField(name = "new_comment_style")
    var newCommentStyle: Int? = null
    @set:UiaJsonField(name = "pending_approval_count")
    var pendingApprovalCount: Int? = null
    @set:UiaJsonField(name = "pic_num")
    var picNum: Int? = null
    @set:UiaJsonField(name = "pic_urls")
    var picUrls: List<Any>? = null
    @set:UiaJsonField(name = "positive_recom_flag")
    var positiveRecomFlag: Int? = null
    @set:UiaJsonField(name = "reposts_count")
    var repostsCount: Int? = null
    @set:UiaJsonField(name = "reprint_cmt_count")
    var reprintCmtCount: Int? = null
    @set:UiaJsonField(name = "reward_exhibition_type")
    var rewardExhibitionType: Int? = null
    @set:UiaJsonField(name = "rid")
    var rid: String? = null
    @set:UiaJsonField(name = "show_additional_indication")
    var showAdditionalIndication: Int? = null
    @set:UiaJsonField(name = "show_mlevel")
    var showMlevel: Int? = null
    @UiaJsonField(name = "source")
    var source: String? = null
    @UiaJsonField(name = "source_allowclick")
    var sourceAllowclick: Int? = null
    @UiaJsonField(name = "source_type")
    var sourceType: Int? = null
    @UiaJsonField(name = "text")
    var text: String? = null
    @UiaJsonField(name = "textLength")
    var textLength: Int? = null
    @UiaJsonField(name = "text_tag_tips")
    var textTagTips: List<Any>? = null
    @UiaJsonField(name = "truncated")
    var truncated: Boolean? = null
    @UiaJsonField(name = "userType")
    var userType: Int? = null
    @UiaJsonField(name = "visible")
    var visible: Visible? = null
}
